FROM rust:1.59

RUN cargo install cargo-make --version 0.35.10

RUN groupadd --gid 1000 app && \
    useradd --uid 1000 --gid app --system app --create-home

USER app

WORKDIR /app

CMD ["tail", "-f", "/dev/null"]
