version: "3"

services:
  web:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "3030:3030"
    volumes:
      - "~/.cargo:/home/app/.cargo"
      - ".:/app"
    environment:
      CARGO_HOME: /home/app/.cargo
    depends_on:
      - frontend
      - scanner
      - geth
      - redis
    command: cargo make web

  scanner:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - "~/.cargo:/home/app/.cargo"
      - ".:/app"
    environment:
      CARGO_HOME: /home/app/.cargo
    depends_on:
      - geth
      - redis
    command: cargo make scanner

  frontend:
    build:
      context: ./docker/frontend
      dockerfile: Dockerfile.dev
    volumes:
      - "~/.cargo:/home/app/.cargo"
      - "./frontend:/app"
    ports:
      - "8080:8080"
    environment:
      CARGO_HOME: /home/app/.cargo

  geth:
    image: ethereum/client-go:alltools-v1.10.7
    restart: unless-stopped
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
      - "8546:8546"
    volumes:
      - "geth_data:/root"
    depends_on:
      - redis
    command: geth --syncmode "light" --ws --ws.addr "0.0.0.0" --ws.api "eth,net,web3,txpool" --http --http.addr "0.0.0.0"
    logging:
      driver: none

  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6901:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"

volumes:
  geth_data:
    driver: local
  redis_data:
    driver: local
