version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile.prod
    ports:
      - "8080:8080"
    depends_on:
      - web
      - scanner
      - redis

  web:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile.prod
    restart: unless-stopped
    depends_on:
      - redis
    env_file: .env.production
    command: eth_oracle_rs

  scanner:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile.prod
    restart: unless-stopped
    depends_on:
      - redis
    env_file: .env.production
    environment:
      WEB3_PROVIDER_URL: ${WEB3_PROVIDER_URL}
    command: scanner

  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - "redis_data:/bitnami/redis/data"

volumes:
  geth_data:
    driver: local
  redis_data:
    driver: local
